language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "ij9FpTk6pIACC4gxlMhE9uCR7WY+yRHmh7Rprgq1y5jLQfReu77XdVw+kssDg5xIWwl7EM7HSYawnj599y/Hxu62oBCbGt2Y8Ez6epBDjrxKFcFtsl3a/O7quozf4EkeMQdW87Jlt6jtrJNVd9ffyQeL4vfVpkzr2zEYuGOIbcBN0UgrylbtRz8AAoEF5Q5bUAhxPLqVBENjoabFDTGG0trsEr3dR2HezJvZRlGbn18q5FjIY1KvN7TvWgy9TdDXQFgYJVNB+Jo2EcQ5d+YmvZMV8UAovP2l58UotPTOiA4Xn2gcukovFp0AxHjEAZEdd3exGe1dn3poBlS9DfEU0wbRXEjfBbQyq+AUQ28yNDPXy4D27r028tzRyhUmr5yrcyrwjuZmSXRMA3NGdE8oyWMmq5hUc4fr3l9ZWqsMsaf0UH5aIzsm4B3PMWTdWu+4mWvJbkD0TE4sXVHrsajrcDtcvmKEZFmbxv7mutdO2yJp/WJwMlJ3rO7VMbOqb3naXSfoXWGDdxtbvO2+8ehfqGLNp9H/fL6a/eM3NDwV81dP3hnVZroFPOQzMzsjSEGD82gvYL5+maO2qb6Kg3v/cUptgq54ZWKsEUeL5XqZGIbzX2f1yEcX6b+nzbeHlmEyUo+RCASEQTi5nT07kYNgU5aIILdCyDZY04YhnBOWug8="
    - secure: "ZvuvehmbiW4RKItjjRokdZdMIhZkLKuZr+CCcu9wRihUj+TvraJ9dADTdbbKlcQVfqqd9+/Hauwsr10k+ZP6PZTyeh4/hvI/BIqlfQNzdwqN8WQ1XxecqspzC9yS1tQnQNcq0nXn4Xyu9KjrAwGYqr1AaKnKLdG7UYVicn5i6eELDniJciVz25k5iaOHa7orFJidZHCuC3nDg8txams8VFMeQgo/KFzYpTBIYAEqtitFve/tHkSwgRuT52kT3K7Wd/M1TrybzfbqurGhp88xZ0mzohiOHf27WGkXFnBsUecGcaI4BZXSjG4JMxNrSkJUw53Fx0fBv2lryyCqfGW4uimxkQDZdFeI93krdYwdL//fWdXDq1OrzMTIPERvUn1ZbFpmCX2sHbseGcLUnP++uZ4UVn9w0a7iplE9Q/om7tPr0r1bDe4ot02bAHjLDYK0pkM4vA7gmDqcqXG3zptrUTWRgVqbSmRN+7CzVQSD8OHM+NxNMbfFc/RvnhQcaaKlJRJofeXldXJD4xoYXd1lSyqOE+KtftB0Og4tIfAhrcgnROssNU8SdQnPf/k9uSb2K5a413Iw5IaUXMnilU6q1hhe7uAg2O2tayAMvJ5YNHCOEWFYu3RpjEnAUBRFyPZjyzoZ68j1BDAPTxXzKBAz70sFYZJWw83iH32kTWJFM7Y="

branches:
  only:
    - master

install:
  - mvn -version -B

script:
  - mvn -fae install | grep -vF "Downloading:" | grep -vF "Downloaded:"

after_success:
  - test "${TRAVIS_PULL_REQUEST}" = "false" && mvn -s .travis.maven.settings.xml -DskipTests=true deploy

notifications:
  email: gary@scribble.org
